### ISSUE TITLE
update cache doesn't work

### ISSUE THREAD

**Issue by captainfodder** [seankndy/circuitsmngr-c#1]
### Description
It would appear that the update cache doesn't work correctly if the user's password contains special characters. When running `c --update-cache -u userName -p pas*w!0rD` it results in the following error: `-bash: !0: event not found` 

Work around: if I escape the password with single quotes then it will work, however double quotes do not.

### Environment
OS: Ubuntu 20.04.3 LTS
Shell: GNU bash
Version: 5.0.17(1)-release

### Suggested Solution:
Instead prompt the user to input their username & password with a read so it isn't stored in their bash history in plain text and this also prevents bash from trying to interpret the enter credentials.
```
read -p "Enter your username: " username
read -sp "Enter your password: " password
echo
```
I included the blank `echo` because the `-s` option for read prevents the user's typing from appearing in the terminal, including the new line usually created after a user presses `Enter` when answering a prompt.

You can then use the $username and $password variables for the rest of your script and the credentials will not have to be stored outside of memory, meaning they will be lost/destroyed after the script completes.

**Comment by seankndy** [comment]
The typical use case is to put the update cache command into your crontab to run at a given interval (daily, for example) and to never run this from your terminal.  This is why the password is taken as an argument and not read interactively.  You can enclose the password in single quotes as you mentioned and you can prevent it from being stored in a history file using bash features like histignore.

**Comment by captainfodder** [comment]
I knew there had to be a reason, just couldn't place my finger on it...
